### ISSUE TITLE
Search app speed

### ISSUE THREAD

**Issue by vtshitoyan** [materialsintelligence/matstract#27]
When searching in the textarea, It gives an error on Heroku:

Process running mem=572M(111.7%)
2018-02-19T04:07:34.218896+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)

And is quite slow. The elastic search we have talked about might make it faster, and solve the error. Otherwise putting manual limits on the results might be a quick solution.

**Comment by jdagdelen** [comment]
Now that we're on ElasticSearch, this is fixed.
