### ISSUE TITLE
When switching between extract app and search app, extract text is transplanted to search box. 

### ISSUE THREAD

**Issue by jdagdelen** [materialsintelligence/matstract#3]
I have no idea why this is happening. Does anyone else know?

**Comment by vtshitoyan** [comment]
I tried a couple of quick things with no luck, also a quick google search didn't give any answers. Seems like this will require more than a few minutes to fix.

**Comment by vtshitoyan** [comment]
Any luck with this? I am having a related problem (I think) when I load random abstracts. Some class names persist even though I load a new abstract, so the highlighting gets messed up. I have pushed this code yet so you can't really test it.

**Comment by jdagdelen** [comment]
Maybe this is something to bring up with the plotly dash devs?

**Comment by vtshitoyan** [comment]
Yes I just posted on the forum, hopefully we will get a reply soon.

**Comment by vtshitoyan** [comment]
I might have found the reason for this. It has to do with React.js dynamic reloading of properties, value being one of those. The correct solution (I think) is to implement a componentWillReceiveProps method, which we can do by extending the dash core component. For now, one easy way to fix it is to wrap one of the textareas in a div, which I have done.
