### ISSUE TITLE
Handle error after downloading files

### ISSUE THREAD

**Issue by vtshitoyan** [materialsintelligence/matstract#35]
matstract/matstract/collect/scopus.py", line 466, in contribute

bson.errors.InvalidDocument: Cannot encode object: HTTPError('404 Client Error: Not Found for url: https://api.elsevier.com/content/article/doi/10.1007/s11263-013-0689-x?view=FULL',)

This happens quite often after the download finishes and crashes the script.

**Comment by jdagdelen** [comment]
This issue should be fixed, but I'm going to keep this issue open for now so we can test for a few days before closing it.
